POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json
Source: "mobile"
device_id: DESKTOP-885PHN8

{
    "username":"MULASS",
    "password":"1234",
    "workspace": 1
}

###

POST http://localhost:3000/auth/verify
Content-Type: text/plain
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjp7ImlkIjoxMDExLCJ1c2VyIjp7ImlkIjoyLCJuciI6MSwidXNlcm5hbWUiOiJNVUxBU1MiLCJuYW1lIjoiTXVoYW1tZWQiLCJzdXJuYW1lIjoiVWxhxZ8iLCJpc0FkbWluIjoxLCJFUlBUb2tlbiI6ImFzZCIsIkxvZ29JZCI6MX0sIndvcmtzcGFjZSI6eyJpZCI6MSwibnIiOjEsInRpdGxlIjoiw4dhbMSxxZ9tYSBBbGFuxLEgMSIsImZpcm1OciI6MjIwLCJwZXJOciI6MX0sImRldmljZSI6eyJpZCI6NTgxLCJuciI6MiwiaWRlbnRpZmllciI6IkRFU0tUT1AtODg1UEhOOCIsImRlZmluaXRpb24iOm51bGx9LCJleHBpcmVzQXQiOjE2NTk4NDcwNTd9LCJpYXQiOjE2NTk4MDM4NTcsImV4cCI6MTY1OTgwNDc1N30.J1DiR-etpA2K6GyZ1Gdv-pExZhykxWZBYUmp3ZopB4U

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiTVVMQVNTIiwidXNlcklkIjoyLCJ1c2VyTnIiOjF9LCJ3b3Jrc3BhY2UiOjEsImlhdCI6MTY1ODk5Mjg2MSwiZXhwIjoxNjU4OTkzNzYxfQ.S0YTLI9-9uB663SzcnLnTK2IO4JpRDG_IeoTrPP0Zl8

{
    "refreshToken":"eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiTVVMQVNTIiwidXNlcklkIjoyLCJ1c2VyTnIiOjF9LCJ3b3Jrc3BhY2UiOjEsImlhdCI6MTY1ODk5Mjg2MSwiZXhwIjoxNjU5MDM2MDYxfQ.QbW7Q0-c3eclfd_LdeII9r2eeYKYpX-0V3m_HH3uxMrDxPv7H0vG0NF3of6PmIWH"
}


###
POST http://localhost:3000/auth/encrypt
Content-Type: application/json

{
    "text":"1234"
}

###
POST http://localhost:3000/auth/decrypt
Content-Type: application/json

{
    "text":"U2FsdGVkX19bivcU/P8VMgKEF/1n9s1A8zJILYVTyy0="
}

###
POST http://localhost:3000/auth/hash
Content-Type: application/json

{
    "text":"1234"
}

###
POST http://localhost:3000/auth/test
Content-Type: application/json
device_id: DESKTOP-885PHN2

{
    "username": "MULASS"
}


###
GET http://localhost:3000/auth/user/MULASS