POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "username":"muhammed",
    "password":"mu123456"
}

###

POST http://localhost:3000/auth/verify
Content-Type: text/plain
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11aGFtbWVkIiwicGFzc3dvcmQiOiJtdTEyMzQ1NiIsImlhdCI6MTY1ODc4NDUzOCwiZXhwIjoxNjU4Nzg1NDM4fQ.KqJqfEv5QpQ9_u5zlB-UCTSHnPhaudNxy8dzfeNEkds

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11aGFtbWVkIiwicGFzc3dvcmQiOiJtdTEyMzQ1NiIsImlhdCI6MTY1ODc4NDUzOCwiZXhwIjoxNjU4Nzg1NDM4fQ.KqJqfEv5QpQ9_u5zlB-UCTSHnPhaudNxy8dzfeNEkds

{
    "refreshToken":"eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11aGFtbWVkIiwicGFzc3dvcmQiOiJtdTEyMzQ1NiIsImlhdCI6MTY1ODc4NDUzOCwiZXhwIjoxNjU4ODI3NzM4fQ.RXwHfeXIo7UrMOkDCg8TxGVSvUEbglfzRUu5lKxsGTFKWD5tUHZ9iT09Bz14MEMb"
}




###
GET http://localhost:3000/users/sync